// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb/internal"
)

var _ = internal.GetEnvOrDefault

// The Honeycomb API key to use. It can also be set via the `HONEYCOMB_API_KEY` or `HONEYCOMBIO_APIKEY` environment
// variables.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "honeycomb:apiKey")
}

// Override the URL of the Honeycomb API. Defaults to `https://api.honeycomb.io`. It can also be set via the
// `HONEYCOMB_API_ENDPOINT` environment variable.
func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "honeycomb:apiUrl")
}

// Enable the API client's debug logs. By default, a `TF_LOG` setting of debug or higher will enable this.
func GetDebug(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "honeycomb:debug")
}
