// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package honeycomb

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb/internal"
)

// ## # Data Source: GetAuthMetadata
//
// The `GetAuthMetadata` data source retreives information about the API key used to authenticate the provider.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			current, err := honeycomb.GetAuthMetadata(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("teamName", current.Team.Name)
//			ctx.Export("environmentSlug", current.Environment.Slug)
//			ctx.Export("sloManagementAccess", current.ApiKeyAccess.Slos)
//			return nil
//		})
//	}
//
// ```
func GetAuthMetadata(ctx *pulumi.Context, args *GetAuthMetadataArgs, opts ...pulumi.InvokeOption) (*GetAuthMetadataResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAuthMetadataResult
	err := ctx.Invoke("honeycomb:index/getAuthMetadata:GetAuthMetadata", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetAuthMetadata.
type GetAuthMetadataArgs struct {
	// The authorizations granted for the API key used to authenticate the provider.
	// See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
	ApiKeyAccess *GetAuthMetadataApiKeyAccess `pulumi:"apiKeyAccess"`
	// Information about the Environment the API key is scoped to.
	Environment *GetAuthMetadataEnvironment `pulumi:"environment"`
	// Information about the Team the API key is scoped to.
	Team *GetAuthMetadataTeam `pulumi:"team"`
}

// A collection of values returned by GetAuthMetadata.
type GetAuthMetadataResult struct {
	// The authorizations granted for the API key used to authenticate the provider.
	// See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
	ApiKeyAccess *GetAuthMetadataApiKeyAccess `pulumi:"apiKeyAccess"`
	// Information about the Environment the API key is scoped to.
	Environment *GetAuthMetadataEnvironment `pulumi:"environment"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Information about the Team the API key is scoped to.
	Team *GetAuthMetadataTeam `pulumi:"team"`
}

func GetAuthMetadataOutput(ctx *pulumi.Context, args GetAuthMetadataOutputArgs, opts ...pulumi.InvokeOption) GetAuthMetadataResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAuthMetadataResult, error) {
			args := v.(GetAuthMetadataArgs)
			r, err := GetAuthMetadata(ctx, &args, opts...)
			var s GetAuthMetadataResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAuthMetadataResultOutput)
}

// A collection of arguments for invoking GetAuthMetadata.
type GetAuthMetadataOutputArgs struct {
	// The authorizations granted for the API key used to authenticate the provider.
	// See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
	ApiKeyAccess GetAuthMetadataApiKeyAccessPtrInput `pulumi:"apiKeyAccess"`
	// Information about the Environment the API key is scoped to.
	Environment GetAuthMetadataEnvironmentPtrInput `pulumi:"environment"`
	// Information about the Team the API key is scoped to.
	Team GetAuthMetadataTeamPtrInput `pulumi:"team"`
}

func (GetAuthMetadataOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAuthMetadataArgs)(nil)).Elem()
}

// A collection of values returned by GetAuthMetadata.
type GetAuthMetadataResultOutput struct{ *pulumi.OutputState }

func (GetAuthMetadataResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAuthMetadataResult)(nil)).Elem()
}

func (o GetAuthMetadataResultOutput) ToGetAuthMetadataResultOutput() GetAuthMetadataResultOutput {
	return o
}

func (o GetAuthMetadataResultOutput) ToGetAuthMetadataResultOutputWithContext(ctx context.Context) GetAuthMetadataResultOutput {
	return o
}

// The authorizations granted for the API key used to authenticate the provider.
// See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
func (o GetAuthMetadataResultOutput) ApiKeyAccess() GetAuthMetadataApiKeyAccessPtrOutput {
	return o.ApplyT(func(v GetAuthMetadataResult) *GetAuthMetadataApiKeyAccess { return v.ApiKeyAccess }).(GetAuthMetadataApiKeyAccessPtrOutput)
}

// Information about the Environment the API key is scoped to.
func (o GetAuthMetadataResultOutput) Environment() GetAuthMetadataEnvironmentPtrOutput {
	return o.ApplyT(func(v GetAuthMetadataResult) *GetAuthMetadataEnvironment { return v.Environment }).(GetAuthMetadataEnvironmentPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAuthMetadataResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAuthMetadataResult) string { return v.Id }).(pulumi.StringOutput)
}

// Information about the Team the API key is scoped to.
func (o GetAuthMetadataResultOutput) Team() GetAuthMetadataTeamPtrOutput {
	return o.ApplyT(func(v GetAuthMetadataResult) *GetAuthMetadataTeam { return v.Team }).(GetAuthMetadataTeamPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAuthMetadataResultOutput{})
}
