// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package honeycomb

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			dataset := cfg.Require("dataset")
//			_, err := honeycomb.GetColumn(ctx, &honeycomb.LookupColumnArgs{
//				Dataset: dataset,
//				Name:    "mycol",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupColumn(ctx *pulumi.Context, args *LookupColumnArgs, opts ...pulumi.InvokeOption) (*LookupColumnResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupColumnResult
	err := ctx.Invoke("honeycomb:index/getColumn:GetColumn", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetColumn.
type LookupColumnArgs struct {
	// The dataset this column is associated with
	Dataset string `pulumi:"dataset"`
	// The name of the column
	Name string `pulumi:"name"`
}

// A collection of values returned by GetColumn.
type LookupColumnResult struct {
	// the ISO8601 formatted time when the column was created
	CreatedAt string `pulumi:"createdAt"`
	Dataset   string `pulumi:"dataset"`
	// the description of the column
	Description string `pulumi:"description"`
	// whether or not the column is hidden from the query builder and results
	Hidden bool `pulumi:"hidden"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// the ISO8601 formatted time that the column last received data
	LastWrittenAt string `pulumi:"lastWrittenAt"`
	Name          string `pulumi:"name"`
	// the type of the column (string, integer, float, or boolean)
	Type string `pulumi:"type"`
	// the  ISO8601 formatted time when the column's metadata (type, description, etc) was last changed
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupColumnOutput(ctx *pulumi.Context, args LookupColumnOutputArgs, opts ...pulumi.InvokeOption) LookupColumnResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupColumnResult, error) {
			args := v.(LookupColumnArgs)
			r, err := LookupColumn(ctx, &args, opts...)
			var s LookupColumnResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupColumnResultOutput)
}

// A collection of arguments for invoking GetColumn.
type LookupColumnOutputArgs struct {
	// The dataset this column is associated with
	Dataset pulumi.StringInput `pulumi:"dataset"`
	// The name of the column
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupColumnOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupColumnArgs)(nil)).Elem()
}

// A collection of values returned by GetColumn.
type LookupColumnResultOutput struct{ *pulumi.OutputState }

func (LookupColumnResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupColumnResult)(nil)).Elem()
}

func (o LookupColumnResultOutput) ToLookupColumnResultOutput() LookupColumnResultOutput {
	return o
}

func (o LookupColumnResultOutput) ToLookupColumnResultOutputWithContext(ctx context.Context) LookupColumnResultOutput {
	return o
}

// the ISO8601 formatted time when the column was created
func (o LookupColumnResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupColumnResultOutput) Dataset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.Dataset }).(pulumi.StringOutput)
}

// the description of the column
func (o LookupColumnResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.Description }).(pulumi.StringOutput)
}

// whether or not the column is hidden from the query builder and results
func (o LookupColumnResultOutput) Hidden() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupColumnResult) bool { return v.Hidden }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupColumnResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.Id }).(pulumi.StringOutput)
}

// the ISO8601 formatted time that the column last received data
func (o LookupColumnResultOutput) LastWrittenAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.LastWrittenAt }).(pulumi.StringOutput)
}

func (o LookupColumnResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.Name }).(pulumi.StringOutput)
}

// the type of the column (string, integer, float, or boolean)
func (o LookupColumnResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.Type }).(pulumi.StringOutput)
}

// the  ISO8601 formatted time when the column's metadata (type, description, etc) was last changed
func (o LookupColumnResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupColumnResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupColumnResultOutput{})
}
