// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package honeycomb

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb/internal"
)

// ## # Data Source: Dataset
//
// The `Dataset` data source retrieves the details of a single Dataset.
// If you want to retrieve multiple Datasets, use the `GetDatasets` data source instead.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/thejokersthief/pulumi-honeycomb/sdk/go/honeycomb"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := honeycomb.GetDataset(ctx, &honeycomb.LookupDatasetArgs{
//				Slug: "my-service",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupDataset(ctx *pulumi.Context, args *LookupDatasetArgs, opts ...pulumi.InvokeOption) (*LookupDatasetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDatasetResult
	err := ctx.Invoke("honeycomb:index/getDataset:GetDataset", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetDataset.
type LookupDatasetArgs struct {
	// The Slug of the Dataset
	Slug string `pulumi:"slug"`
}

// A collection of values returned by GetDataset.
type LookupDatasetResult struct {
	// ISO8601-formatted time the dataset was created.
	CreatedAt string `pulumi:"createdAt"`
	// the current state of the Dataset's deletion protection status.
	DeleteProtected bool `pulumi:"deleteProtected"`
	// the Dataset's description.
	Description string `pulumi:"description"`
	// The Dataset's maximum unpacking depth of nested JSON fields.
	ExpandJsonDepth float64 `pulumi:"expandJsonDepth"`
	Id              string  `pulumi:"id"`
	// ISO8601-formatted time the dataset was last written to (received event data).
	LastWrittenAt string `pulumi:"lastWrittenAt"`
	// the Dataset's name.
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func LookupDatasetOutput(ctx *pulumi.Context, args LookupDatasetOutputArgs, opts ...pulumi.InvokeOption) LookupDatasetResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDatasetResult, error) {
			args := v.(LookupDatasetArgs)
			r, err := LookupDataset(ctx, &args, opts...)
			var s LookupDatasetResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDatasetResultOutput)
}

// A collection of arguments for invoking GetDataset.
type LookupDatasetOutputArgs struct {
	// The Slug of the Dataset
	Slug pulumi.StringInput `pulumi:"slug"`
}

func (LookupDatasetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDatasetArgs)(nil)).Elem()
}

// A collection of values returned by GetDataset.
type LookupDatasetResultOutput struct{ *pulumi.OutputState }

func (LookupDatasetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDatasetResult)(nil)).Elem()
}

func (o LookupDatasetResultOutput) ToLookupDatasetResultOutput() LookupDatasetResultOutput {
	return o
}

func (o LookupDatasetResultOutput) ToLookupDatasetResultOutputWithContext(ctx context.Context) LookupDatasetResultOutput {
	return o
}

// ISO8601-formatted time the dataset was created.
func (o LookupDatasetResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDatasetResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// the current state of the Dataset's deletion protection status.
func (o LookupDatasetResultOutput) DeleteProtected() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDatasetResult) bool { return v.DeleteProtected }).(pulumi.BoolOutput)
}

// the Dataset's description.
func (o LookupDatasetResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDatasetResult) string { return v.Description }).(pulumi.StringOutput)
}

// The Dataset's maximum unpacking depth of nested JSON fields.
func (o LookupDatasetResultOutput) ExpandJsonDepth() pulumi.Float64Output {
	return o.ApplyT(func(v LookupDatasetResult) float64 { return v.ExpandJsonDepth }).(pulumi.Float64Output)
}

func (o LookupDatasetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDatasetResult) string { return v.Id }).(pulumi.StringOutput)
}

// ISO8601-formatted time the dataset was last written to (received event data).
func (o LookupDatasetResultOutput) LastWrittenAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDatasetResult) string { return v.LastWrittenAt }).(pulumi.StringOutput)
}

// the Dataset's name.
func (o LookupDatasetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDatasetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDatasetResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDatasetResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDatasetResultOutput{})
}
