# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiKey: Optional[str]
"""
The Honeycomb API key to use. It can also be set via the `HONEYCOMB_API_KEY` or `HONEYCOMBIO_APIKEY` environment
variables.
"""

apiUrl: Optional[str]
"""
Override the URL of the Honeycomb API. Defaults to `https://api.honeycomb.io`. It can also be set via the
`HONEYCOMB_API_ENDPOINT` environment variable.
"""

debug: Optional[bool]
"""
Enable the API client's debug logs. By default, a `TF_LOG` setting of debug or higher will enable this.
"""

