// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Resource: honeycomb.Environment
 *
 * Creates a Honeycomb Environment.
 *
 * > **NOTE** This resource requires the provider be configured with a Management Key with `environments:write` in the configured scopes.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const uat = new honeycomb.Environment("uat", {color: "green"});
 * ```
 *
 * ## Import
 *
 * Environments can be imported by their ID. e.g.
 *
 * ```sh
 * $ pulumi import honeycomb:index/environment:Environment myenv hcaen_01j1jrsewaha3m0z6fwffpcrxg
 * ```
 */
export class Environment extends pulumi.CustomResource {
    /**
     * Get an existing Environment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EnvironmentState, opts?: pulumi.CustomResourceOptions): Environment {
        return new Environment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'honeycomb:index/environment:Environment';

    /**
     * Returns true if the given object is an instance of Environment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Environment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Environment.__pulumiType;
    }

    /**
     * The color to display the Environment in the navigation bar.
     * If not provided one will be randomly selected at creation.
     * One of `blue`, `green`, `gold`, `red`, `purple`, `lightBlue`, `lightGreen`, `lightGold`, `lightRed`, `lightPurple`.
     */
    public readonly color!: pulumi.Output<string>;
    /**
     * the current state of the Environment's deletion protection status.
     * Defaults to `true`. Cannot be set to `false` on create.
     */
    public readonly deleteProtected!: pulumi.Output<boolean>;
    /**
     * A description for the Environment.
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * The name of the Environment. Must be unique to the Team.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The slug of the Environment.
     */
    public /*out*/ readonly slug!: pulumi.Output<string>;

    /**
     * Create a Environment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EnvironmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EnvironmentArgs | EnvironmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EnvironmentState | undefined;
            resourceInputs["color"] = state ? state.color : undefined;
            resourceInputs["deleteProtected"] = state ? state.deleteProtected : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as EnvironmentArgs | undefined;
            resourceInputs["color"] = args ? args.color : undefined;
            resourceInputs["deleteProtected"] = args ? args.deleteProtected : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Environment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Environment resources.
 */
export interface EnvironmentState {
    /**
     * The color to display the Environment in the navigation bar.
     * If not provided one will be randomly selected at creation.
     * One of `blue`, `green`, `gold`, `red`, `purple`, `lightBlue`, `lightGreen`, `lightGold`, `lightRed`, `lightPurple`.
     */
    color?: pulumi.Input<string>;
    /**
     * the current state of the Environment's deletion protection status.
     * Defaults to `true`. Cannot be set to `false` on create.
     */
    deleteProtected?: pulumi.Input<boolean>;
    /**
     * A description for the Environment.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the Environment. Must be unique to the Team.
     */
    name?: pulumi.Input<string>;
    /**
     * The slug of the Environment.
     */
    slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Environment resource.
 */
export interface EnvironmentArgs {
    /**
     * The color to display the Environment in the navigation bar.
     * If not provided one will be randomly selected at creation.
     * One of `blue`, `green`, `gold`, `red`, `purple`, `lightBlue`, `lightGreen`, `lightGold`, `lightRed`, `lightPurple`.
     */
    color?: pulumi.Input<string>;
    /**
     * the current state of the Environment's deletion protection status.
     * Defaults to `true`. Cannot be set to `false` on create.
     */
    deleteProtected?: pulumi.Input<boolean>;
    /**
     * A description for the Environment.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the Environment. Must be unique to the Team.
     */
    name?: pulumi.Input<string>;
}
