// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # Data Source: honeycomb.GetAuthMetadata
 *
 * The `honeycomb.GetAuthMetadata` data source retreives information about the API key used to authenticate the provider.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const current = honeycomb.GetAuthMetadata({});
 * export const teamName = current.then(current => current.team?.name);
 * export const environmentSlug = current.then(current => current.environment?.slug);
 * export const sloManagementAccess = current.then(current => current.apiKeyAccess?.slos);
 * ```
 */
export function getAuthMetadata(args?: GetAuthMetadataArgs, opts?: pulumi.InvokeOptions): Promise<GetAuthMetadataResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getAuthMetadata:GetAuthMetadata", {
        "apiKeyAccess": args.apiKeyAccess,
        "environment": args.environment,
        "team": args.team,
    }, opts);
}

/**
 * A collection of arguments for invoking GetAuthMetadata.
 */
export interface GetAuthMetadataArgs {
    /**
     * The authorizations granted for the API key used to authenticate the provider.
     * See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
     */
    apiKeyAccess?: inputs.GetAuthMetadataApiKeyAccess;
    /**
     * Information about the Environment the API key is scoped to.
     */
    environment?: inputs.GetAuthMetadataEnvironment;
    /**
     * Information about the Team the API key is scoped to.
     */
    team?: inputs.GetAuthMetadataTeam;
}

/**
 * A collection of values returned by GetAuthMetadata.
 */
export interface GetAuthMetadataResult {
    /**
     * The authorizations granted for the API key used to authenticate the provider.
     * See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
     */
    readonly apiKeyAccess?: outputs.GetAuthMetadataApiKeyAccess;
    /**
     * Information about the Environment the API key is scoped to.
     */
    readonly environment?: outputs.GetAuthMetadataEnvironment;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Information about the Team the API key is scoped to.
     */
    readonly team?: outputs.GetAuthMetadataTeam;
}
/**
 * ## # Data Source: honeycomb.GetAuthMetadata
 *
 * The `honeycomb.GetAuthMetadata` data source retreives information about the API key used to authenticate the provider.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const current = honeycomb.GetAuthMetadata({});
 * export const teamName = current.then(current => current.team?.name);
 * export const environmentSlug = current.then(current => current.environment?.slug);
 * export const sloManagementAccess = current.then(current => current.apiKeyAccess?.slos);
 * ```
 */
export function getAuthMetadataOutput(args?: GetAuthMetadataOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAuthMetadataResult> {
    return pulumi.output(args).apply((a: any) => getAuthMetadata(a, opts))
}

/**
 * A collection of arguments for invoking GetAuthMetadata.
 */
export interface GetAuthMetadataOutputArgs {
    /**
     * The authorizations granted for the API key used to authenticate the provider.
     * See [the documentation](https://docs.honeycomb.io/working-with-your-data/settings/api-keys/) for more information.
     */
    apiKeyAccess?: pulumi.Input<inputs.GetAuthMetadataApiKeyAccessArgs>;
    /**
     * Information about the Environment the API key is scoped to.
     */
    environment?: pulumi.Input<inputs.GetAuthMetadataEnvironmentArgs>;
    /**
     * Information about the Team the API key is scoped to.
     */
    team?: pulumi.Input<inputs.GetAuthMetadataTeamArgs>;
}
