// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const config = new pulumi.Config();
 * const dataset = config.require("dataset");
 * const mycol = honeycomb.GetColumn({
 *     dataset: dataset,
 *     name: "mycol",
 * });
 * ```
 */
export function getColumn(args: GetColumnArgs, opts?: pulumi.InvokeOptions): Promise<GetColumnResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getColumn:GetColumn", {
        "dataset": args.dataset,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking GetColumn.
 */
export interface GetColumnArgs {
    /**
     * The dataset this column is associated with
     */
    dataset: string;
    /**
     * The name of the column
     */
    name: string;
}

/**
 * A collection of values returned by GetColumn.
 */
export interface GetColumnResult {
    /**
     * the ISO8601 formatted time when the column was created
     */
    readonly createdAt: string;
    readonly dataset: string;
    /**
     * the description of the column
     */
    readonly description: string;
    /**
     * whether or not the column is hidden from the query builder and results
     */
    readonly hidden: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * the ISO8601 formatted time that the column last received data
     */
    readonly lastWrittenAt: string;
    readonly name: string;
    /**
     * the type of the column (string, integer, float, or boolean)
     */
    readonly type: string;
    /**
     * the  ISO8601 formatted time when the column's metadata (type, description, etc) was last changed
     */
    readonly updatedAt: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const config = new pulumi.Config();
 * const dataset = config.require("dataset");
 * const mycol = honeycomb.GetColumn({
 *     dataset: dataset,
 *     name: "mycol",
 * });
 * ```
 */
export function getColumnOutput(args: GetColumnOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetColumnResult> {
    return pulumi.output(args).apply((a: any) => getColumn(a, opts))
}

/**
 * A collection of arguments for invoking GetColumn.
 */
export interface GetColumnOutputArgs {
    /**
     * The dataset this column is associated with
     */
    dataset: pulumi.Input<string>;
    /**
     * The name of the column
     */
    name: pulumi.Input<string>;
}
