// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const config = new pulumi.Config();
 * const dataset = config.require("dataset");
 * const mydc = honeycomb.GetDerivedColumn({
 *     dataset: dataset,
 *     alias: "mydc",
 * });
 * ```
 */
export function getDerivedColumn(args: GetDerivedColumnArgs, opts?: pulumi.InvokeOptions): Promise<GetDerivedColumnResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getDerivedColumn:GetDerivedColumn", {
        "alias": args.alias,
        "dataset": args.dataset,
    }, opts);
}

/**
 * A collection of arguments for invoking GetDerivedColumn.
 */
export interface GetDerivedColumnArgs {
    /**
     * The alias of the column
     */
    alias: string;
    /**
     * The dataset this derived column is associated with. Use `__all__` for Environment-wide derived columns.
     */
    dataset: string;
}

/**
 * A collection of values returned by GetDerivedColumn.
 */
export interface GetDerivedColumnResult {
    readonly alias: string;
    readonly dataset: string;
    /**
     * the description of the derived column
     */
    readonly description: string;
    /**
     * the expression of the derived column
     */
    readonly expression: string;
    /**
     * the ID of the derived column.
     */
    readonly id: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const config = new pulumi.Config();
 * const dataset = config.require("dataset");
 * const mydc = honeycomb.GetDerivedColumn({
 *     dataset: dataset,
 *     alias: "mydc",
 * });
 * ```
 */
export function getDerivedColumnOutput(args: GetDerivedColumnOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDerivedColumnResult> {
    return pulumi.output(args).apply((a: any) => getDerivedColumn(a, opts))
}

/**
 * A collection of arguments for invoking GetDerivedColumn.
 */
export interface GetDerivedColumnOutputArgs {
    /**
     * The alias of the column
     */
    alias: pulumi.Input<string>;
    /**
     * The dataset this derived column is associated with. Use `__all__` for Environment-wide derived columns.
     */
    dataset: pulumi.Input<string>;
}
