// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Data Source: honeycomb.Dataset
 *
 * The `honeycomb.Dataset` data source retrieves the details of a single Dataset.
 * If you want to retrieve multiple Datasets, use the `honeycomb.GetDatasets` data source instead.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const my-service = honeycomb.GetDataset({
 *     slug: "my-service",
 * });
 * ```
 */
export function getDataset(args: GetDatasetArgs, opts?: pulumi.InvokeOptions): Promise<GetDatasetResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getDataset:GetDataset", {
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking GetDataset.
 */
export interface GetDatasetArgs {
    /**
     * The Slug of the Dataset
     */
    slug: string;
}

/**
 * A collection of values returned by GetDataset.
 */
export interface GetDatasetResult {
    /**
     * ISO8601-formatted time the dataset was created.
     */
    readonly createdAt: string;
    /**
     * the current state of the Dataset's deletion protection status.
     */
    readonly deleteProtected: boolean;
    /**
     * the Dataset's description.
     */
    readonly description: string;
    /**
     * The Dataset's maximum unpacking depth of nested JSON fields.
     */
    readonly expandJsonDepth: number;
    readonly id: string;
    /**
     * ISO8601-formatted time the dataset was last written to (received event data).
     */
    readonly lastWrittenAt: string;
    /**
     * the Dataset's name.
     */
    readonly name: string;
    readonly slug: string;
}
/**
 * ## # Data Source: honeycomb.Dataset
 *
 * The `honeycomb.Dataset` data source retrieves the details of a single Dataset.
 * If you want to retrieve multiple Datasets, use the `honeycomb.GetDatasets` data source instead.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const my-service = honeycomb.GetDataset({
 *     slug: "my-service",
 * });
 * ```
 */
export function getDatasetOutput(args: GetDatasetOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatasetResult> {
    return pulumi.output(args).apply((a: any) => getDataset(a, opts))
}

/**
 * A collection of arguments for invoking GetDataset.
 */
export interface GetDatasetOutputArgs {
    /**
     * The Slug of the Dataset
     */
    slug: pulumi.Input<string>;
}
