// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getQueryResult(args: GetQueryResultArgs, opts?: pulumi.InvokeOptions): Promise<GetQueryResultResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getQueryResult:GetQueryResult", {
        "dataset": args.dataset,
        "queryJson": args.queryJson,
    }, opts);
}

/**
 * A collection of arguments for invoking GetQueryResult.
 */
export interface GetQueryResultArgs {
    /**
     * The dataset this query is associated with. Use `__all__` for Environment-wide queries.
     */
    dataset: string;
    /**
     * A JSON object describing the query according to the Query Specification. While the JSON can be constructed manually, it is easiest to use the honeycomb.GetQuerySpecification data source.
     */
    queryJson: string;
}

/**
 * A collection of values returned by GetQueryResult.
 */
export interface GetQueryResultResult {
    readonly dataset: string;
    readonly graphImageUrl: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The ID of the Query created and executed to obtain the result.
     */
    readonly queryId: string;
    readonly queryJson: string;
    /**
     * The permalink to the executed query's results.
     */
    readonly queryUrl: string;
    readonly results: {[key: string]: string}[];
}
export function getQueryResultOutput(args: GetQueryResultOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetQueryResultResult> {
    return pulumi.output(args).apply((a: any) => getQueryResult(a, opts))
}

/**
 * A collection of arguments for invoking GetQueryResult.
 */
export interface GetQueryResultOutputArgs {
    /**
     * The dataset this query is associated with. Use `__all__` for Environment-wide queries.
     */
    dataset: pulumi.Input<string>;
    /**
     * A JSON object describing the query according to the Query Specification. While the JSON can be constructed manually, it is easiest to use the honeycomb.GetQuerySpecification data source.
     */
    queryJson: pulumi.Input<string>;
}
