// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export function getRecipient(args: GetRecipientArgs, opts?: pulumi.InvokeOptions): Promise<GetRecipientResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getRecipient:GetRecipient", {
        "dataset": args.dataset,
        "detailFilter": args.detailFilter,
        "target": args.target,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking GetRecipient.
 */
export interface GetRecipientArgs {
    /**
     * Deprecated: recipients are now a Team-level construct. Any provided value will be ignored.
     *
     * @deprecated Recipients are now a Team-level construct. The provided 'dataset' value is being ignored and should be removed.
     */
    dataset?: string;
    /**
     * a block to further filter recipients as described below.
     */
    detailFilter?: inputs.GetRecipientDetailFilter;
    /**
     * Deprecated: use `detailFilter` instead. The target of the recipient, this has another meaning depending on the type of recipient (see the table below).
     *
     * Type      | Target
     * ----------|-------------------------
     * email     | an email address
     * marker    | name of the marker
     * msteams   | name of the integration
     * pagerduty | _N/A_
     * slack     | name of the channel
     * webhook   | name of the webhook
     *
     * @deprecated Use of 'target' has been replaced by 'detail_filter'.
     */
    target?: string;
    /**
     * The type of recipient, allowed types are `email`, `pagerduty`, `msteams`, `slack` and `webhook`.
     */
    type: string;
}

/**
 * A collection of values returned by GetRecipient.
 */
export interface GetRecipientResult {
    /**
     * The email recipient's address -- if of type `email`.
     */
    readonly address: string;
    /**
     * The Slack recipient's channel -- if of type `slack`.
     */
    readonly channel: string;
    /**
     * @deprecated Recipients are now a Team-level construct. The provided 'dataset' value is being ignored and should be removed.
     */
    readonly dataset?: string;
    readonly detailFilter?: outputs.GetRecipientDetailFilter;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * (Sensitive) The PagerDuty recipient's integration key -- if of type `pagerduty`.
     */
    readonly integrationKey: string;
    /**
     * The PagerDuty recipient's inregration name -- if of type `pagerduty`.
     */
    readonly integrationName: string;
    /**
     * The webhook recipient's name -- if of type `webhook` or `msteams`.
     */
    readonly name: string;
    /**
     * (Sensitive) The webhook recipient's secret -- if of type `webhook`.
     */
    readonly secret: string;
    /**
     * @deprecated Use of 'target' has been replaced by 'detail_filter'.
     */
    readonly target?: string;
    readonly type: string;
    /**
     * The webhook recipient's URL - if of type `webhook` or `msteams`.
     */
    readonly url: string;
}
/**
 * ## Example Usage
 */
export function getRecipientOutput(args: GetRecipientOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRecipientResult> {
    return pulumi.output(args).apply((a: any) => getRecipient(a, opts))
}

/**
 * A collection of arguments for invoking GetRecipient.
 */
export interface GetRecipientOutputArgs {
    /**
     * Deprecated: recipients are now a Team-level construct. Any provided value will be ignored.
     *
     * @deprecated Recipients are now a Team-level construct. The provided 'dataset' value is being ignored and should be removed.
     */
    dataset?: pulumi.Input<string>;
    /**
     * a block to further filter recipients as described below.
     */
    detailFilter?: pulumi.Input<inputs.GetRecipientDetailFilterArgs>;
    /**
     * Deprecated: use `detailFilter` instead. The target of the recipient, this has another meaning depending on the type of recipient (see the table below).
     *
     * Type      | Target
     * ----------|-------------------------
     * email     | an email address
     * marker    | name of the marker
     * msteams   | name of the integration
     * pagerduty | _N/A_
     * slack     | name of the channel
     * webhook   | name of the webhook
     *
     * @deprecated Use of 'target' has been replaced by 'detail_filter'.
     */
    target?: pulumi.Input<string>;
    /**
     * The type of recipient, allowed types are `email`, `pagerduty`, `msteams`, `slack` and `webhook`.
     */
    type: pulumi.Input<string>;
}
