// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Data Source: honeycomb.GetSLO
 *
 * The `honeycomb.GetSLO` data source retrieves the details of a single SLO for a dataset.
 * If you want to retreive multiple SLOs, use the `honeycomb.GetSLOs` data source instead.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const config = new pulumi.Config();
 * const dataset = config.require("dataset");
 * const myslo = honeycomb.GetSLO({
 *     dataset: dataset,
 *     id: "fS4WfA82ACt",
 * });
 * ```
 */
export function getSLO(args: GetSLOArgs, opts?: pulumi.InvokeOptions): Promise<GetSLOResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("honeycomb:index/getSLO:GetSLO", {
        "dataset": args.dataset,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking GetSLO.
 */
export interface GetSLOArgs {
    /**
     * The dataset this SLO is associated with
     */
    dataset: string;
    /**
     * The ID of the SLO
     */
    id: string;
}

/**
 * A collection of values returned by GetSLO.
 */
export interface GetSLOResult {
    readonly dataset: string;
    /**
     * the SLO's description.
     */
    readonly description: string;
    readonly id: string;
    /**
     * the name of the SLO.
     */
    readonly name: string;
    /**
     * the alias of the Derived Column used as the SLO's SLI.
     */
    readonly sli: string;
    /**
     * the percentage of qualified events expected to succeed during the `timePeriod`.
     */
    readonly targetPercentage: number;
    /**
     * The time period, in days, over which the SLO is evaluated.
     */
    readonly timePeriod: number;
}
/**
 * ## # Data Source: honeycomb.GetSLO
 *
 * The `honeycomb.GetSLO` data source retrieves the details of a single SLO for a dataset.
 * If you want to retreive multiple SLOs, use the `honeycomb.GetSLOs` data source instead.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const config = new pulumi.Config();
 * const dataset = config.require("dataset");
 * const myslo = honeycomb.GetSLO({
 *     dataset: dataset,
 *     id: "fS4WfA82ACt",
 * });
 * ```
 */
export function getSLOOutput(args: GetSLOOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSLOResult> {
    return pulumi.output(args).apply((a: any) => getSLO(a, opts))
}

/**
 * A collection of arguments for invoking GetSLO.
 */
export interface GetSLOOutputArgs {
    /**
     * The dataset this SLO is associated with
     */
    dataset: pulumi.Input<string>;
    /**
     * The ID of the SLO
     */
    id: pulumi.Input<string>;
}
