// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Resource: honeycomb.WebhookRecipient
 *
 * `honeycomb.WebhookRecipient` allows you to define and manage a Webhook recipient that can be used by Triggers or BurnAlerts notifications.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as honeycomb from "@pulumi/honeycomb";
 *
 * const prod = new honeycomb.WebhookRecipient("prod", {
 *     secret: "a63dab148496ecbe04a1a802ca9b95b8",
 *     url: "https://my.url.corp.net",
 * });
 * ```
 *
 * ## Import
 *
 * Webhook Recipients can be imported by their ID, e.g.
 *
 * ```sh
 * $ pulumi import honeycomb:index/webhookRecipient:WebhookRecipient my_recipient nx2zsegA0dZ
 * ```
 */
export class WebhookRecipient extends pulumi.CustomResource {
    /**
     * Get an existing WebhookRecipient resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookRecipientState, opts?: pulumi.CustomResourceOptions): WebhookRecipient {
        return new WebhookRecipient(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'honeycomb:index/webhookRecipient:WebhookRecipient';

    /**
     * Returns true if the given object is an instance of WebhookRecipient.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WebhookRecipient {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WebhookRecipient.__pulumiType;
    }

    /**
     * The name of the Webhook Integration to create.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The secret to include when sending the notification to the webhook.
     */
    public readonly secret!: pulumi.Output<string>;
    /**
     * The URL of the endpoint to send the notification to.
     */
    public readonly url!: pulumi.Output<string>;

    /**
     * Create a WebhookRecipient resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookRecipientArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookRecipientArgs | WebhookRecipientState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookRecipientState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as WebhookRecipientArgs | undefined;
            if ((!args || args.secret === undefined) && !opts.urn) {
                throw new Error("Missing required property 'secret'");
            }
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["secret"] = args?.secret ? pulumi.secret(args.secret) : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(WebhookRecipient.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WebhookRecipient resources.
 */
export interface WebhookRecipientState {
    /**
     * The name of the Webhook Integration to create.
     */
    name?: pulumi.Input<string>;
    /**
     * The secret to include when sending the notification to the webhook.
     */
    secret?: pulumi.Input<string>;
    /**
     * The URL of the endpoint to send the notification to.
     */
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a WebhookRecipient resource.
 */
export interface WebhookRecipientArgs {
    /**
     * The name of the Webhook Integration to create.
     */
    name?: pulumi.Input<string>;
    /**
     * The secret to include when sending the notification to the webhook.
     */
    secret: pulumi.Input<string>;
    /**
     * The URL of the endpoint to send the notification to.
     */
    url: pulumi.Input<string>;
}
